name: "Validate JSON files and deploy to GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.17

      - name: Install dependencies
        working-directory: scripts
        run: bun install

      - name: Implode overrides
        working-directory: scripts
        run: bun run implodeOverrides

      - name: Implode overrides
        working-directory: scripts
        run: bun run validate

      - name: Validate schema
        working-directory: scripts
        run: bun run validate

      - name: Update .gitignore
        working-directory: scripts
        run: echo '!overrides/*' >> .gitignore

      - name: Push to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          clean: true
